[versions]
guava = "33.4.6-jre"
junit-jupiter = "5.12.1"
flatlaf = "3.5"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
