[versions]
java = "21"
guava = "33.1.0-jre"
flatlaf = "3.5"
httpclient5 = "5.3.1"
poi = "5.4.0"
commons-lang3 = "3.18.0"
sqlite-jdbc = "3.45.3.0"
junit-jupiter = "5.10.2"
junit-platform = "1.10.2"
assertj = "3.25.3"
jmockit = "1.49"


[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
httpclient5-fluent = { module = "org.apache.httpcomponents.client5:httpclient5-fluent", version.ref = "httpclient5" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jmockit = { module = "org.jmockit:jmockit", version.ref = "jmockit" }



